# Generated by Django 4.2.2 on 2024-04-03 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_title', models.CharField(max_length=255, unique=True, verbose_name='branch_title')),
            ],
            options={
                'db_table': 'branch',
                'ordering': ['branch_title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['category_title'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='full_name')),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('sex', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='М', max_length=1, verbose_name='sex')),
                ('address', models.CharField(max_length=96, verbose_name='address')),
                ('phone', models.CharField(max_length=64, verbose_name='phone')),
            ],
            options={
                'db_table': 'client',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='full_name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_category', to='center.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_category', to='center.category')),
            ],
            options={
                'db_table': 'doctor',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_title', models.CharField(max_length=128, unique=True, verbose_name='kind_title')),
            ],
            options={
                'db_table': 'kind',
                'ordering': ['kind_title'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_title', models.CharField(max_length=255, unique=True, verbose_name='specialization_title')),
            ],
            options={
                'db_table': 'specialization',
                'ordering': ['specialization_title'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visit', models.DateTimeField(verbose_name='date_visit')),
                ('visit_details', models.TextField(blank=True, null=True, verbose_name='visit_details')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_client', to='center.client')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_doctor', to='center.doctor')),
            ],
            options={
                'db_table': 'visit',
                'ordering': ['date_visit'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=256, verbose_name='service_title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='service_price')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_kind', to='center.kind')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['service_title'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='monday', max_length=16, verbose_name='week_day')),
                ('time_schedule', models.CharField(max_length=64, verbose_name='time_schedule')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_doctor', to='center.doctor')),
            ],
            options={
                'db_table': 'schedule',
                'ordering': ['week_day'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='sale_price')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_service', to='center.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_visit', to='center.visit')),
            ],
            options={
                'db_table': 'sale',
                'ordering': ['service'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialization', to='center.specialization'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnosis', models.DateTimeField(verbose_name='date_diagnosis')),
                ('diagnosis_details', models.TextField(blank=True, null=True, verbose_name='diagnosis_details')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_client', to='center.client')),
            ],
            options={
                'db_table': 'diagnosis',
                'ordering': ['client'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['full_name'], name='client_full_na_f03115_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['client'], name='visit_client__64dd8c_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['doctor'], name='visit_doctor__b7b5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['kind', 'service_title'], name='service_kind_id_00625e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['doctor'], name='schedule_doctor__969bff_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['visit'], name='sale_visit_i_27e1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['service'], name='sale_service_d2b048_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['full_name'], name='doctor_full_na_32003f_idx'),
        ),
    ]
